const express = require("express");
const cors = require("cors");
const connectToDatabase = require("./database/connect");
const router = express.Router();
const app = express();

const userRoutes = require("./routes/user.routes");
const roleRoutes = require("./routes/role.routes");
const lojasRoutes = require("./routes/lojas.routes");
const produtosRoutes = require("./routes/produtos.routes");
const produtosSercice = require("./routes/produtosSite.routes.js");
const clientesRoutes = require("./routes/clientes.routes");
const fornecedoresRoutes = require("./routes/fornecedores.routes");
const cidadesRoutes = require("./routes/cidades.routes");
const gruposRoutes = require("./routes/grupos.routes");
const orcamantosRoutes = require("./routes/orcamentos.routes");
const caixaRoutes = require("./routes/caixa.routes");
const receberRoutes = require("./routes/receber.routes");
const vendasRoutes = require("./routes/vendas.routes");
const entradasRoutes = require("./routes/entradas.routes");
const saidasRoutes = require("./routes/saidas.routes");
const categoriaContabilRoutes = require("./routes/categoriaContabilRoutes.routes");
const contasBancariasRoutes = require("./routes/contasBancariasRoutes.routes");
const servicosRoutes = require("./routes/servicosRoutes.routes");
const osRoutes = require("./routes/osRoutes.routes");
const mecanicosRoutes = require("./routes/mecanicosRoutes.routes");
const pagarRoutes = require("./routes/pagar.routes");
const landingPageRoutes = require("./routes/landingPage.routes");
const auth = require("./middlewares/auth");

app.use(cors());
app.use(express.json());
app.use(router);

app.use("/usuario", userRoutes);
app.use("/lojas", lojasRoutes);

app.use("/roles", auth, roleRoutes);
app.use("/produtos", auth, produtosRoutes);
app.use("/produtosCatalogo", produtosSercice);
app.use("/clientes", auth, clientesRoutes);
app.use("/fornecedores", auth, fornecedoresRoutes);
app.use("/cidades", auth, cidadesRoutes);
app.use("/grupos", auth, gruposRoutes);
app.use("/orcamentos", auth, orcamantosRoutes);
app.use("/caixa", auth, caixaRoutes);
app.use("/receber", auth, receberRoutes);
app.use("/vendas", auth, vendasRoutes);
app.use("/entradas", auth, entradasRoutes);
app.use("/saidas", auth, saidasRoutes);
app.use("/categoriaContabil", auth, categoriaContabilRoutes);
app.use("/contasBancarias", auth, contasBancariasRoutes);
app.use("/os", auth, osRoutes);
app.use("/servicos", auth, servicosRoutes);
app.use("/mecanicos", auth, mecanicosRoutes);
app.use("/pagar", auth, pagarRoutes);
app.use("/landingPage", auth, landingPageRoutes);

connectToDatabase();
module.exports = app;
